name: Release

on:
  release:
    types: [created]

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build project
      run: |
        npm install
        npm run build

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/index.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
